### ISSUE TITLE
100 Day Goal

### ISSUE THREAD

**Issue by mmockus** [mmockus/100_Days_of_HomeLab#7]
- [x] [Set 100 day goal](https://github.com/mmockus/100_Days_of_HomeLab/issues/1)
- [x] [Build a server using cloud=init](https://github.com/mmockus/100_Days_of_HomeLab/issues/2)
- [x] [Establish SSH login to all servers](https://github.com/mmockus/100_Days_of_HomeLab/issues/3)
- [ ] Rebuild TrueNas Core to TrueNas Scale
- [ ] Create a Portainer server
- [ ] Create a kubernetes cluster
  - [ ] Rancher
  - [ ] Longhorn
  - [ ] Harvester
- [ ] Deploy a workload on Kubernetes
- [ ] Do something in Codespaces
- [ ] Automate a server configure from Github
- [ ] Create a proxy server
- [ ] [Apache Guacomole](https://guacamole.apache.org/)
- [ ] pihole gravity-sync
- [ ] Grafana Server
- [ ] Host certificate on Proxy server
- [ ] Establish VPN
